# fly.toml app configuration file generated for nera-chat-service
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "nera-chat-service"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8001"

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
